language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
